// <auto-generated />
using System;
using CountyRP.WebAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountyRP.WebAPI.Migrations.Property
{
    [DbContext(typeof(PropertyContext))]
    partial class PropertyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CountyRP.DAO.ATM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<long>("Dimension")
                        .HasColumnType("bigint");

                    b.Property<string>("_Position")
                        .HasColumnName("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ATMs");
                });

            modelBuilder.Entity("CountyRP.DAO.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EntranceDimension")
                        .HasColumnType("bigint");

                    b.Property<long>("ExitDimension")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("_EntrancePosition")
                        .HasColumnName("EntrancePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_ExitPosition")
                        .HasColumnName("ExitPosition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("CountyRP.DAO.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EntranceDimension")
                        .HasColumnType("bigint");

                    b.Property<float>("EntranceRotation")
                        .HasColumnType("real");

                    b.Property<long>("ExitDimension")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("_EntrancePosition")
                        .HasColumnName("EntrancePosition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Garages");
                });

            modelBuilder.Entity("CountyRP.DAO.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EntranceDimension")
                        .HasColumnType("bigint");

                    b.Property<long>("ExitDimension")
                        .HasColumnType("bigint");

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<long>("SafeDimension")
                        .HasColumnType("bigint");

                    b.Property<int>("SafeInventoryId")
                        .HasColumnType("int");

                    b.Property<string>("_EntrancePosition")
                        .HasColumnName("EntrancePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_ExitPosition")
                        .HasColumnName("ExitPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_SafePosition")
                        .HasColumnName("SafePosition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("CountyRP.DAO.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("ColorBlip")
                        .HasColumnType("tinyint");

                    b.Property<long>("EntranceDimension")
                        .HasColumnType("bigint");

                    b.Property<long>("ExitDimension")
                        .HasColumnType("bigint");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPayment")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<long>("SafeDimension")
                        .HasColumnType("bigint");

                    b.Property<int>("TypeBlip")
                        .HasColumnType("int");

                    b.Property<int>("TypeMarker")
                        .HasColumnType("int");

                    b.Property<string>("_ColorMarker")
                        .HasColumnName("ColorMarker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_EntrancePosition")
                        .HasColumnName("EntrancePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_ExitPosition")
                        .HasColumnName("ExitPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_SafePosition")
                        .HasColumnName("SafePosition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CountyRP.DAO.Teleport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<byte>("ColorBlip")
                        .HasColumnType("tinyint");

                    b.Property<long>("EntranceDimension")
                        .HasColumnType("bigint");

                    b.Property<long>("ExitDimension")
                        .HasColumnType("bigint");

                    b.Property<string>("FactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GangId")
                        .HasColumnType("int");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("TypeBlip")
                        .HasColumnType("int");

                    b.Property<int>("TypeMarker")
                        .HasColumnType("int");

                    b.Property<string>("_ColorMarker")
                        .HasColumnName("ColorMarker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_EntrancePosition")
                        .HasColumnName("EntrancePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_ExitPosition")
                        .HasColumnName("ExitPosition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teleports");
                });

            modelBuilder.Entity("CountyRP.DAO.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color1")
                        .HasColumnType("int");

                    b.Property<int>("Color2")
                        .HasColumnType("int");

                    b.Property<long>("Dimension")
                        .HasColumnType("bigint");

                    b.Property<string>("FactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fuel")
                        .HasColumnType("float");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<float>("Rotation")
                        .HasColumnType("real");

                    b.Property<string>("_Position")
                        .HasColumnName("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
